---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mysql_instance
    image: "docker.io/library/ubuntu:22.04"
    published_ports:
      - "3306:3306"
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      mysql_instance:
        ansible_connection: docker
        wp_mysql_db: "wordpress"
        wp_mysql_user: "datascientest"
        wp_mysql_password: "dbpassword"
        wp_mysql_host: "mysql_instance"
verifier:
  name: testinfra
