---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "docker.io/library/ubuntu:20.04"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
