---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mysql_instance
    image: "mysql:8.0-debian"
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "datascientest"
      MYSQL_PASSWORD: "dbpassword"
      MYSQL_ROOT_PASSWORD: "Datascientest2022"
    pre_build_image: true
    exposed_ports:
      - "3306"
provisioner:
  name: ansible
  inventory:
    host_vars:
      mysql_instance:
        ansible_connection: docker
        wp_mysql_db: "wordpress"
        wp_mysql_user: "datascientest"
        wp_mysql_password: "dbpassword"
        wp_mysql_host: "mysql_instance"
        mysql_root_password: "Datascientest2022"
verifier:
  name: testinfra
