- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install sudo and python3
      raw: apt-get update && apt-get install -y sudo python3 mysql-server
      become: false

    - name: Set python3 as the ansible python interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: Ensure MySQL is configured to use socket
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^socket'
        line: 'socket=/var/run/mysqld/mysqld.sock'
        state: present
      become: true
    
    - name: restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted
      become: true