---
# tasks file for wordpress
- name: WordPress | Install php
  apt:
    pkg:
      [
        "php-pear",
        "php-fpm",
        "php-dev",
        "php-zip",
        "php-curl",
        "php-xmlrpc",
        "php-gd",
        "php-mysql",
        "php-mbstring",
        "php-xml",
      ]
    update_cache: yes
    cache_valid_time: 86400
    state: present

- name: Wordpress | Install MySQL client
  apt:
    name: mysql-client-core-8.0
    state: present

- name: Wordpress | Install nginx
  apt:
    pkg: nginx
    update_cache: yes
    cache_valid_time: 86400
    state: present
  when: wp_webserver == "nginx"

- name: WordPress | remove /var/www/html/
  file:
    path: /var/www/html/index.html
    state: absent
  when: wp_install_dir == "/var/www/html"

- name: WordPress | create directory
  file:
    path: "{{ wp_install_dir }}"
    state: directory
    mode: 0755

- name: WordPress | extract wp archive in {{ wp_install_dir }}
  unarchive:
    src: "http://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: "{{ wp_install_dir }}"
    remote_src: yes
    creates: "{{ wp_install_dir }}/wp-config-sample.php"

- name: Check if the WordPress directory exists
  stat:
    path: "{{ wp_install_dir }}/wordpress"
  register: wp_dir

- name: Find WordPress files to move
  find:
    paths: "{{ wp_install_dir }}/wordpress"
  register: files_to_move
  when: wp_dir.stat.exists and wp_dir.stat.isdir

- name: Move files from /var/www/html/demo.com/wordpress to /var/www/html/demo.com if necessary
  command: mv "{{ item.path }}" "{{ wp_install_dir }}/"
  loop: "{{ files_to_move.files }}"
  when: 
    - wp_dir.stat.exists and wp_dir.stat.isdir
    - files_to_move.files | length > 0

- name: WordPress | delete wordpress directory
  file:
    path: "{{ wp_install_dir }}/wordpress/"
    state: absent
  when: wp_dir.stat.exists and wp_dir.stat.isdir

- name: WordPress | salts for wp-config.php
  delegate_to: localhost
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  become: False
  register: "wp_salt_array"
  changed_when: false

- name: define wp_salt fact
  set_fact:
    wp_salt: "{{ wp_salt_array.content }}"
  changed_when: false

- name: Check if wp-config.php needs an update
  stat:
    path: "{{ wp_install_dir }}/wp-config.php"
  register: wp_config

- name: WordPress | wp-config.php copy
  template:
    src: wp-config.php.j2
    dest: "{{ wp_install_dir }}/wp-config.php"
  when: not wp_config.stat.exists

- name: WordPress | change owner of install dir
  file:
    path: "{{ wp_install_dir }}"
    owner: www-data
    group: www-data
    state: directory
    recurse: yes

- include_tasks: nginx.yml
  when: wp_webserver == "nginx"