---
# tasks file for mysql
- name: install mysql-server
  apt:
    pkg: mysql-server
    update_cache: yes
    cache_valid_time: 86400
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install mariadb-server
  apt:
    pkg: mariadb-server
    update_cache: yes
    cache_valid_time: 86400
    state: present
  when: ansible_distribution == 'Debian'

- name: start MariaDB
  service:
    name: mysql
    state: started
    enabled: yes

- name: install dependencies
  apt:
    pkg: ["php-mysql", "python3-pymysql"]
    update_cache: yes
    cache_valid_time: 86400
    state: present

#####################

- name: create root user
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    plugin: mysql_native_password
    priv: '*.*:ALL,GRANT'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Save root password in .my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'

  ####################

- name: create database
  mysql_db:
    name: "{{ wp_mysql_db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user and grant privileges
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ wp_mysql_user }}"
    host: '%'
    password: "{{ wp_mysql_password }}"
    priv: '*.*:ALL,GRANT'
    append_privs: yes
    state: present

- name: allow remote connection
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address"
    line: "bind-address = 0.0.0.0"
    state: present
  notify: restart mysql