---
- name: Converge
  hosts: all
  tasks:
    - name: "Include mysql"
      include_role:
        name: ../../roles/mysql
    - name: "Include wordpress"
      include_role:
        name: ../../roles/wordpress
