---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: wordpress_molecule_instance
    image: "docker.io/library/ubuntu:22.04"
    pre_build_image: true
    depends_on:
      - mysql_molecule_instance
provisioner:
  name: ansible
  inventory:
    host_vars:
      wordpress_molecule_instance:
        ansible_connection: docker
        wp_version: "latest"
        wp_webserver: "nginx"
        wp_admin_email: "joel.lourenco.pro@gmail.com"
        wp_sitename: "exam-ansible"
        wp_install_dir: "/var/www/html/demo.com"
        wp_db_name: "wordpress"
        wp_db_user: "datascientest"
        wp_db_password: "dbpassword"
        wp_db_host: "mysql_instance"
        wp_db_charset: "utf8"
        wp_debug: "True"
verifier:
  name: testinfra
